version: "3.8"
services:
  frontend:
    build:
      context: ./frontend-devops
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
  
  backend:
    build:
      context: ./backend-devops
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=techdome

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: techdome
    volumes:
      - db-data:/var/lib/postgresql/data
  
volumes:
  db-data:
